name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.1
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=3.0.0-290.1.beta <4.0.0'

dependencies:
  crypto: ^3.0.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  quiver: ^3.0.1
  hive: ^2.2.2
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
