name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  path: ^1.8.0
  quiver: ^3.1.0
  sqflite: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
